const BASE = 'https://api.trello.com/1'

function authQuery(key, token) {
  return `key=${encodeURIComponent(key)}&token=${encodeURIComponent(token)}`
}

async function handle(res) {
  if (!res.ok) {
    const text = await res.text().catch(() => '')
    throw new Error(`Trello ${res.status}: ${text || res.statusText}`)
  }
  return res.json()
}

export async function createCard({ key, token, listId, name, desc = '' }) {
  const res = await fetch(`${BASE}/cards?${authQuery(key, token)}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ idList: listId, name, desc })
  })
  return handle(res)
}

export async function attachImage({ key, token, cardId, file, name }) {
  const form = new FormData()
  form.append('file', file)
  if (name) form.append('name', name)
  const res = await fetch(
    `${BASE}/cards/${cardId}/attachments?${authQuery(key, token)}`,
    { method: 'POST', body: form }
  )
  return handle(res)
}

export async function updateCard({ key, token, cardId, fields }) {
  const res = await fetch(`${BASE}/cards/${cardId}?${authQuery(key, token)}`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(fields)
  })
  return handle(res)
}

export async function listBoards({ key, token }) {
  const res = await fetch(
    `${BASE}/members/me/boards?fields=name,id&${authQuery(key, token)}`
  )
  return handle(res)
}

export async function listLists({ key, token, boardId }) {
  const res = await fetch(
    `${BASE}/boards/${boardId}/lists?fields=name,id&${authQuery(key, token)}`
  )
  return handle(res)
}

// Trả về list[] mỗi cái có array `cards` lồng bên trong — dùng để render picker
export async function listListsWithCards({ key, token, boardId }) {
  const res = await fetch(
    `${BASE}/boards/${boardId}/lists?cards=open&card_fields=name,id&fields=name,id&${authQuery(
      key,
      token
    )}`
  )
  return handle(res)
}

// Lấy attachments của 1 card — trả về [{id, name, url, mimeType, fileName, bytes, isUpload}]
export async function listAttachments({ key, token, cardId }) {
  const res = await fetch(
    `${BASE}/cards/${cardId}/attachments?${authQuery(key, token)}`
  )
  return handle(res)
}

// Download binary của 1 attachment.
// Strategy 1 (CORS-friendly): hit URL trong `previews[]` (S3 signed URL, browser fetch OK)
// Strategy 2 (fallback): hit endpoint /download/ cần OAuth header (thường bị CORS chặn)
//
// Nếu cả 2 đều fail → throw error rõ ràng để UI gợi ý upload local.
export async function downloadAttachment({
  attachment,
  key,
  token,
  cardId,
  attachmentId,
  fileName
}) {
  // Strategy 1: previews
  const previews = (attachment?.previews || []).filter(p => p?.url)
  if (previews.length > 0) {
    const sorted = [...previews].sort(
      (a, b) =>
        (b.width || 0) * (b.height || 0) -
        (a.width || 0) * (a.height || 0)
    )
    for (const p of sorted) {
      try {
        const res = await fetch(p.url, { mode: 'cors' })
        if (res.ok) return await res.blob()
      } catch {
        // try next preview
      }
    }
  }

  // Strategy 2: authenticated /download endpoint (may fail with CORS)
  const safeName = encodeURIComponent(
    fileName || attachment?.fileName || attachment?.name || 'file'
  )
  const id = attachmentId || attachment?.id
  if (!id) throw new Error('Missing attachment id')
  const url = `${BASE}/cards/${cardId}/attachments/${id}/download/${safeName}`
  let res
  try {
    res = await fetch(url, {
      headers: {
        Authorization: `OAuth oauth_consumer_key="${key}", oauth_token="${token}"`
      }
    })
  } catch (err) {
    throw new Error(
      `CORS block — browser không cho fetch attachment Trello trực tiếp. ` +
        `Dùng nút "+ Upload local" để chọn file mockup từ máy. (${err.message})`
    )
  }
  if (!res.ok) {
    const text = await res.text().catch(() => '')
    throw new Error(`Trello download ${res.status}: ${text || res.statusText}`)
  }
  return res.blob()
}

export function buildCardDesc({
  sku,
  title,
  tags,
  attempts,
  titleValid,
  tagsValid,
  mockupCount
}) {
  const tagsLine = Array.isArray(tags) && tags.length ? tags.join(', ') : null
  const warnings = []
  if (titleValid === false) warnings.push('Title format chưa chuẩn (130-140 ký tự, đuôi SVG/PNG)')
  if (tagsValid === false) warnings.push('Tags chưa đủ 13 hoặc có tag > 20 ký tự')

  return [
    sku ? `**SKU:** ${sku}` : null,
    title ? `**Title:** ${title}` : null,
    tagsLine ? `**Tags (13):**\n${tagsLine}` : null,
    mockupCount ? `**Mockups:** ${mockupCount} JPG + 1 PNG gốc` : null,
    attempts && attempts > 1 ? `**Retries:** ${attempts}` : null,
    warnings.length ? `**⚠ ${warnings.join(' · ')}**` : null,
    '',
    '---',
    '*Generated by Etsy Tool*'
  ]
    .filter(x => x !== null)
    .join('\n')
}
